### ISSUE TITLE
cross-hatch static on clothing

### ISSUE THREAD

**Issue by mycomedico** [yuvraj108c/4k-video-upscaler-colab#5] opened 2024-03-10 15:05 UTC
I'm getting a strange artifact as a result of ERSGAN for my video test case.  Here is a link you can see the artifact at the beginning of this clip.  It's like a fine cross hatched area of static that changes size.  This happens throughout my clip.  any suggestions how to prevent this artifact in the upscaling process?

https://drive.google.com/file/d/1--Zi-4HNoXS7OzyZcuAvysxR7-osAC4S/view?usp=drive_link

**Comment by yuvraj108c** [comment] 2024-03-15 16:21
hmm, the link is invalid @mycomedico 
Try to use the realesrgan_4x model

**Comment by mycomedico** [comment] 2024-03-15 16:33
It looks like this is normal artifact on this model...i tested it several other places and get the same result.

**Comment by yuvraj108c** [comment] 2024-03-23 20:27
ok, closing it since it is an expected behaviour of the model as you mentioned.

**Closed as completed by yuvraj108c** 2024-03-23 20:27 UTC
